name: test
on:
  pull_request:
    types: 
      - closed
  push:
    branches:
      - main
      - master

jobs:
  build: 
    if: github.repository == 'koiNoCirculation/IcyCraft' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      REPO: ${{github.repository}}
      EVENT: ${{github.event.pull_request.merge == true}}
    steps:
      - run: echo $REPO
      - run: echo $EVENT
