name: test
on:
  pull_request:

jobs:
  build: 
    if: github.repository == 'koiNoCirculation/IcyCraft'
    runs-on: ubuntu-latest
    env:
      REPO: ${{github.repository}}
      EVENT: ${{github.event.pull_request.merge}}
    steps:
      - run: echo $REPO
